### ISSUE TITLE
Team Fortress 2/tf/custom/materials as a search path Error.

### ISSUE THREAD

**Issue by Pepper0ni** [cremator-2fort/ULTRAHUD-TF2#4]
> Tried to add /home/pepper0ni/.local/share/Steam/steamapps/common/Team Fortress 2/tf/custom/materials as a search path.
> 
> This is probably not what you intended.
> 
> Check /home/pepper0ni/.local/share/Steam/steamapps/common/Team Fortress 2/tf/custom/readme.txt for more info

I'm trying to install ultrahud on arch Linux alongside mastercomfig, but am consistently getting this error when starting TF2 with it added to /tf/custom. Mastcomfig alone works fine (assuming -precachefontchars is removed, as that causes a crash on start). The error occurs on both current and legacy. 

Issue also exists on 1.5, the error is not new with the recent ultrahud update.

**Comment by h43ven** [comment]
Is there a `materials` directory in tf/custom? If there is, check to see
what is inside. If it contains ULTRAHUD assets, move the materials folder
into the huds folder, if its empty, then feel free to delete it.

Sorry if this isn't much help, Im at school right now and can't do much
involving the HUD.

**Comment by Pepper0ni** [comment]
That's fine, I'm probably following a bad set of hud install instructions, as I didn't even have a huds folder. The video i watched just told me to dump the folder contents into tf/custom. 

When I put all 4 folders into tf/custom/huds/ the game booted, but it was a horrible frankenstien of the vanilla and ultrakill huds, so I am probably still doing something wrong. Leaving any ultrakill folder in tf/custom root gave a variant of the error though. I'm going to see if I can find better HUD install instructions in the mean time.

EDIT: following rayshud instructions, I re-downloaded and put the whole folder into tf/custom insted of extracting the contents into it, which had no visual effect in game but made a tf/custom/ultrahud-tf2 folder. when moving the other files there the game locked up and crashed after booting in the same way as if  -precachefontchars was a launch option.

**Comment by h43ven** [comment]
Oh, what you should be doing is placing the "ULTRAHUD-TF2" folder into
custom. Don't place it into a subfolder, and don't place the contents
directly in custom, TF2 doesn't like that for some reason.

**Comment by Pepper0ni** [comment]
OK, that's similar to what I did in the edit, but i tried it again and it didn't crash and seems to be working just fine. I have a few other minor things but they aren't bugs so much as customizations I would want, so I'll close this now. Is there anywhere where I could talk more casually about this hud and hud stuff in general?

**Comment by h43ven** [comment]
Whilst I don't have a place to talk about ULTRAHUD in specific, a good
place to talk about huds more casually is the HUDS.TF discord. Other HUD
devs are also on there.
