### ISSUE TITLE
Loading background is missing when connecting to any server

### ISSUE THREAD

**Issue by tekunotri** [cremator-2fort/ULTRAHUD-TF2#6]
self-explained

i could probably fix this by remaking how backgrounds are loaded in `materials/console` so let me know if you want that
![image](https://github.com/cremator-2fort/ULTRAHUD-TF2/assets/41777800/ddcce759-cbce-43dc-8d66-cc07810961db)

**Comment by h43ven** [comment]
Yeah, would appreciate that getting fixed.
